# Generated by Django 6.0.2 on 2026-03-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo_pago', models.AutoField(db_column='id_metodo_pago', primary_key=True, serialize=False)),
                ('nombre_metodo', models.CharField(db_column='nombre_metodo', max_length=50)),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=255, null=True)),
            ],
            options={
                'db_table': 'metodos_pago',
                'ordering': ['nombre_metodo'],
            },
        ),
    ]
