# Generated by Django 6.0.2 on 2026-03-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metodos_pago', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metodopago',
            options={'managed': False, 'ordering': ['nombre_metodo']},
        ),
    ]
