# Generated by Django 6.0.3 on 2026-07-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodos_pago', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodopago',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
