"""Datos del menú alineados con los archivos en static/img/menu/."""

CATEGORIAS = [
    {'nombre': 'Entradas', 'emoji': '🍽️', 'activo': True, 'orden': 1},
    {'nombre': 'Platos Principales', 'emoji': '🍲', 'activo': True, 'orden': 2},
    {'nombre': 'Adiciones', 'emoji': '🍚', 'activo': True, 'orden': 3},
    {'nombre': 'Bebidas', 'emoji': '🍷', 'activo': True, 'orden': 4},
]

# imagen: ruta relativa dentro de static/ (img/menu/archivo.avif)
PLATILLOS = [
    {
        'nombre': 'Ceviche Clásico',
        'descripcion': 'Pescado fresco marinado en jugo de limón, cebolla morada y cilantro.',
        'categoria': 'Entradas',
        'precio': 20000,
        'imagen': 'img/menu/Ceviche-Clásico.avif',
        'emojis': '🐠🍋‍🟩',
        'disponible': True,
        'destacado': True,
        'orden': 1,
    },
    {
        'nombre': 'Tacos de Camarón',
        'descripcion': 'Tortillas de maíz rellenas de camarones a la parrilla, salsa de mango y aguacate.',
        'categoria': 'Entradas',
        'precio': 30000,
        'imagen': 'img/menu/Tacos de Camarón.avif',
        'emojis': '🦐🥭🥑🌽',
        'disponible': True,
        'destacado': True,
        'orden': 2,
    },
    {
        'nombre': 'Pulpo a la Parrilla',
        'descripcion': 'Pulpo tierno asado a la parrilla, servido con salsa de ajo y pimientos.',
        'categoria': 'Entradas',
        'precio': 50000,
        'imagen': 'img/menu/PulpoParrilla.avif',
        'emojis': '🐙🧄🫑',
        'disponible': True,
        'destacado': False,
        'orden': 3,
    },
    {
        'nombre': 'Sopa de Mariscos',
        'descripcion': 'Camarones, almejas y calamares en un fondo aromatizado con especias.',
        'categoria': 'Entradas',
        'precio': 25000,
        'imagen': 'img/menu/SopaMariscos.avif',
        'emojis': '🐠🍋🌿',
        'disponible': True,
        'destacado': False,
        'orden': 4,
    },
    {
        'nombre': 'Paella de Mariscos',
        'descripcion': 'Arroz con una mezcla de mariscos frescos, azafrán y verduras.',
        'categoria': 'Platos Principales',
        'precio': 80000,
        'imagen': 'img/menu/PaellaMariscos.avif',
        'emojis': '🐠🌿',
        'disponible': True,
        'destacado': True,
        'orden': 1,
    },
    {
        'nombre': 'Filete de Salmón',
        'descripcion': 'Salmón a la plancha con salsa de limón y hierbas, acompañado de espárragos.',
        'categoria': 'Platos Principales',
        'precio': 90000,
        'imagen': 'img/menu/Filete de Salmón.avif',
        'emojis': '🐠🍋🌿',
        'disponible': True,
        'destacado': True,
        'orden': 2,
    },
    {
        'nombre': 'Langosta al Horno',
        'descripcion': 'Langosta horneada con mantequilla de ajo y hierbas, servida con puré de papas.',
        'categoria': 'Platos Principales',
        'precio': 110000,
        'imagen': 'img/menu/Langosta al Horno.avif',
        'emojis': '🦞🧄🌿',
        'disponible': True,
        'destacado': True,
        'orden': 3,
    },
    {
        'nombre': 'Filete de Pescado en Salsa de Coco',
        'descripcion': 'Filete de pescado blanco a la plancha, bañado en salsa cremosa de coco con jengibre y limón.',
        'categoria': 'Platos Principales',
        'precio': 80000,
        'imagen': 'img/menu/Filete de Pescado en Salsa de Coco.avif',
        'emojis': '🐠🍋🥥',
        'disponible': True,
        'destacado': False,
        'orden': 4,
    },
    {
        'nombre': 'Camarones',
        'descripcion': 'Porción de camarones frescos, salteados en aceite de oliva con ajo picado y perejil.',
        'categoria': 'Adiciones',
        'precio': 15000,
        'imagen': 'img/menu/Camarones.avif',
        'emojis': '🦐🌿',
        'disponible': True,
        'destacado': False,
        'orden': 1,
    },
    {
        'nombre': 'Porción de arroz con coco',
        'descripcion': 'Arroz blanco cocido lentamente en leche de coco, con un toque dulce y salado.',
        'categoria': 'Adiciones',
        'precio': 6500,
        'imagen': 'img/menu/Porción de arroz con coco.avif',
        'emojis': '🥥🍚',
        'disponible': True,
        'destacado': False,
        'orden': 2,
    },
    {
        'nombre': 'Patacones crocantes',
        'descripcion': 'Rodajas de plátano verde fritas, acompañadas con suero costeño artesanal.',
        'categoria': 'Adiciones',
        'precio': 6000,
        'imagen': 'img/menu/Patacones crocantes.avif',
        'emojis': '🧂',
        'disponible': True,
        'destacado': False,
        'orden': 3,
    },
    {
        'nombre': 'Vegetales salteados',
        'descripcion': 'Zanahoria, brócoli, pimentón y cebolla salteados en mantequilla con pimienta y orégano.',
        'categoria': 'Adiciones',
        'precio': 6500,
        'imagen': 'img/menu/Vegetales salteados.avif',
        'emojis': '🧈🥕🫑🧅',
        'disponible': True,
        'destacado': False,
        'orden': 4,
    },
    {
        'nombre': 'Coctel frutos rojos',
        'descripcion': 'Coctel refrescante con hielo, frutos rojos y rodaja de limón.',
        'categoria': 'Bebidas',
        'precio': 25000,
        'imagen': 'img/menu/Coctel frutos rojos.avif',
        'emojis': '🍒🧊',
        'disponible': True,
        'destacado': True,
        'orden': 1,
    },
    {
        'nombre': 'Jugo tropical',
        'descripcion': 'Jugo fresco con mezcla de frutas tropicales y hielo.',
        'categoria': 'Bebidas',
        'precio': 15000,
        'imagen': 'img/menu/Jugo tropical.avif',
        'emojis': '🥭🧊',
        'disponible': True,
        'destacado': False,
        'orden': 2,
    },
    {
        'nombre': 'Vino intenso',
        'descripcion': 'Vino tinto intenso con notas de frutas negras y maduras.',
        'categoria': 'Bebidas',
        'precio': 42000,
        'imagen': 'img/menu/Vino intenso.avif',
        'emojis': '🍇🧊',
        'disponible': True,
        'destacado': True,
        'orden': 3,
    },
    {
        'nombre': 'Whisky',
        'descripcion': 'Destilado añejado en barricas de madera, con notas ahumadas y especiadas.',
        'categoria': 'Bebidas',
        'precio': 35000,
        'imagen': 'img/menu/Whisky.avif',
        'emojis': '🍯🪵🧊',
        'disponible': True,
        'destacado': False,
        'orden': 4,
    },
    {
        'nombre': 'Sauvignon Blanc',
        'descripcion': 'Refrescante y herbal, con frutas tropicales y acidez vibrante.',
        'categoria': 'Bebidas',
        'precio': 34000,
        'imagen': 'img/menu/Sauvignon Blanc.avif',
        'emojis': '🍷🧊',
        'disponible': True,
        'destacado': False,
        'orden': 5,
    },
    {
        'nombre': 'Vermentino',
        'descripcion': 'Vino blanco fresco con notas cítricas, manzana verde y un toque salino.',
        'categoria': 'Bebidas',
        'precio': 32000,
        'imagen': 'img/menu/Vermentino.avif',
        'emojis': '🍋🧊',
        'disponible': True,
        'destacado': False,
        'orden': 6,
    },
]
