# Generated by Django 6.0.3 on 2026-03-31 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metodos_pago', '0001_initial'),
        ('platillos', '0002_auto_20260327_2143'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('DELIVERY', 'Delivery'), ('LOCAL', 'Local')], max_length=10, null=True)),
            ],
            options={
                'db_table': 'pedidos_cliente',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, default='PENDIENTE', max_length=255, null=True)),
                ('estado_cocina', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_mesero', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('id_adicional', models.IntegerField(blank=True, null=True)),
                ('id_platillo', models.IntegerField(blank=True, null=True)),
                ('nombre_platillo', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('precio_unitario', models.FloatField(blank=True, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True)),
                ('id_cliente', models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.cliente')),
                ('id_metodo_pago', models.ForeignKey(blank=True, db_column='id_metodo_pago', null=True, on_delete=django.db.models.deletion.SET_NULL, to='metodos_pago.metodopago')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pedidos_pedido',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_platillo', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido')),
                ('platillo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platillos.platillo')),
            ],
            options={
                'verbose_name': 'Item del Pedido',
                'verbose_name_plural': 'Items del Pedido',
                'db_table': 'pedidos_item',
            },
        ),
    ]
