# Generated by Django 6.0.3 on 2026-04-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_cocina',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('EN_PREPARACION', 'En preparación'), ('LISTO', 'Listo'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=20, null=True),
        ),
    ]
