# Generated by Django 6.0.2 on 2026-03-13 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
        ('usuarios', '0003_alter_rol_options_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario'),
        ),
    ]
