# Generated by Django 6.0.3 on 2026-03-28 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodos_pago', '0001_initial'),
        ('pedidos', '0003_auto_20260325_1911'),
        ('platillos', '0002_auto_20260327_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='id_metodo_pago',
            field=models.ForeignKey(blank=True, db_column='id_metodo_pago', null=True, on_delete=django.db.models.deletion.SET_NULL, to='metodos_pago.metodopago'),
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_platillo', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido')),
                ('platillo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platillos.platillo')),
            ],
            options={
                'verbose_name': 'Item del Pedido',
                'verbose_name_plural': 'Items del Pedido',
                'db_table': 'pedidos_item',
            },
        ),
    ]
