# Generated by Django 5.2.1 on 2026-05-30 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPlatillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='platillo',
            name='imagen',
        ),
        migrations.AddField(
            model_name='platillo',
            name='emojis',
            field=models.CharField(default='🍽️', max_length=100),
        ),
        migrations.AddField(
            model_name='platillo',
            name='imagen_url',
            field=models.CharField(default='/img/default.jpg', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='platillo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.categoriaplatillo'),
        ),
    ]
