# Generated by Django 6.0.2 on 2026-03-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rol_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'managed': False, 'ordering': ['nombre_rol']},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False, 'ordering': ['nombre_usuario']},
        ),
    ]
