# Generated by Django 6.0.3 on 2026-06-13 16:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_registroactividad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={},
        ),
        migrations.AddField(
            model_name='rol',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rol',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('INACTIVO', 'Inactivo')], db_index=True, default='ACTIVO', max_length=12),
        ),
        migrations.AddField(
            model_name='rol',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='rol',
            table=None,
        ),
    ]
