# Generated by Django 6.0.2 on 2026-02-26 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=150)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_actual', models.IntegerField()),
                ('stock_minimo', models.IntegerField()),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.unidadmedida')),
            ],
        ),
    ]
