# Generated by Django 6.0.3 on 2026-06-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_unidadmedida_abreviatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadmedida',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
