# Generated by Django 6.0.3 on 2026-03-28 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platillos', '0001_initial'),
    ]

    operations = [
    ]
