# Generated by Django 6.0.2 on 2026-06-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['-fecha'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='compradetalle',
            options={'verbose_name': 'Detalle de Compra', 'verbose_name_plural': 'Detalles de Compras'},
        ),
        migrations.AddField(
            model_name='compra',
            name='empresa',
            field=models.CharField(default='Proveedor General', help_text='Nombre del proveedor o empresa a quien se le compra', max_length=100, verbose_name='Nombre de la Empresa/Proveedor'),
        ),
        migrations.AlterField(
            model_name='compradetalle',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
