# Generated by Django 6.0.3 on 2026-06-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_compra_options_alter_compradetalle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='empresa',
            field=models.CharField(help_text='Nombre del proveedor o empresa a quien se le compra', max_length=100, verbose_name='Nombre de la Empresa/Proveedor'),
        ),
    ]
