# Generated by Django 6.0.3 on 2026-07-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_compra_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('ANULADA', 'Anulada')], default='ACTIVA', max_length=20),
        ),
    ]
